name: Publish docker image to GHCR

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: dsosd/io

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -t $IMAGE_NAME -f main_docker .

      - name: Run tests
        run: echo "no tests so we're ok"

      - name: Login to GHCR
        #CR_PAT is personal access token saved as a GH actions secret with `read:packages` and `write:packages` scopes
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GHCR
        run: |
          IMAGE_ID=ghcr.io/$IMAGE_NAME

          VERSION=$(cat .version)

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          #assume this version is latest version
          #TODO maybe do comparison with current latest version
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push $IMAGE_ID:latest
